version: '3'
services:
    node:
        build: .
        ports:
            - '3000:3000'
            - '9229:9229'
        volumes:
            - ./app:/srv/app
        container_name: node
        command: node --inspect=0.0.0.0:9229 /srv/app/app.js
